Fill missing data

In [29]:
import numpy as np
import pandas as pd

In [42]:
baseDeDados = pd.read_csv('svbr.csv', delimiter=';')
X = baseDeDados.iloc[:,:].values
print(X)

[['Site Arqueologia Egípcia' 13438.0 406590.0]
 ['Terra Negra' 35241.0 868235.0]
 ['Frank Jaava' 31680.0 2856508.0]
 ['Dispersciência' 25100.0 150000.0]
 ['Olá Ciência' 32788.0 1575456.0]
 ['A matemaníaca por Julia Jaccoud' 65453.0 1667892.0]
 ['Delta T - Os super lentos' 12000.0 171361.0]
 ['Bláblálogia' 161951.0 11027386.0]
 ['Efarsas' 78876.0 6226235.0]
 ['Minuto da Terra' 274196.0 30166457.0]
 ['Canal Cura Quântica' 13148.0 250020.0]
 ['Mensageiro Sideral' 72425.0 7551491.0]
 ['Universo Racionalista' 7858.0 43662.0]
 ['Xadrez Verbal' 110549.0 4151548.0]
 ['Reinaldo José Lopes' 11188.0 541832.0]
 ["Bio's Fera" 5299.0 44312.0]
 ['QuerQueDesenhe' 56006.0 1329268.0]
 ['Prof André Azevedo da Fonseca' 45756.0 1825724.0]
 ['Matemática Rio com Prof Rafael Procópio' 1423056.0 93036517.0]
 ['Ponto em Comum' 129466.0 5027880.0]
 ['Canal do Slow' 137409.0 5363423.0]
 ['Boteco Behaviorista' 18404.0 1427977.0]
 ['Papo de Primata' 42063.0 1111334.0]
 ['Minutos Psíquicos' 648892.0 22555134.0]
 ['A

In [44]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
imputer = imputer.fit(X[:,1:3])
X = imputer.transform(X[:,1:3]).astype(str)
X = np.insert(X, 0, baseDeDados.iloc[:,0].values, axis=1)
print(X)

[['Site Arqueologia Egípcia' '13438.0' '406590.0']
 ['Terra Negra' '35241.0' '868235.0']
 ['Frank Jaava' '31680.0' '2856508.0']
 ['Dispersciência' '25100.0' '150000.0']
 ['Olá Ciência' '32788.0' '1575456.0']
 ['A matemaníaca por Julia Jaccoud' '65453.0' '1667892.0']
 ['Delta T - Os super lentos' '12000.0' '171361.0']
 ['Bláblálogia' '161951.0' '11027386.0']
 ['Efarsas' '78876.0' '6226235.0']
 ['Minuto da Terra' '274196.0' '30166457.0']
 ['Canal Cura Quântica' '13148.0' '250020.0']
 ['Mensageiro Sideral' '72425.0' '7551491.0']
 ['Universo Racionalista' '7858.0' '43662.0']
 ['Xadrez Verbal' '110549.0' '4151548.0']
 ['Reinaldo José Lopes' '11188.0' '541832.0']
 ["Bio's Fera" '5299.0' '44312.0']
 ['QuerQueDesenhe' '56006.0' '1329268.0']
 ['Prof André Azevedo da Fonseca' '45756.0' '1825724.0']
 ['Matemática Rio com Prof Rafael P' '1423056.0' '93036517.0']
 ['Ponto em Comum' '129466.0' '5027880.0']
 ['Canal do Slow' '137409.0' '5363423.0']
 ['Boteco Behaviorista' '18404.0' '1427977.0']
 ['Pa

Category Variables and split train and test

In [67]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

In [68]:
database = pd.read_csv('admission.csv',delimiter=';')
print(database)

      Name  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0    Lucas        337          118                  4  4.5  4.5  9.65   
1      Ana        324          107                  4  4.0  4.5  8.87   
2     Jose        316          104                  3  3.0  3.5  8.00   
3   Carlos        322          110                  3  3.5  2.5  8.67   
4  Zileide        314          103                  2  2.0  3.0  8.21   
5    Joana        330          115                  5  4.5  3.0  9.34   
6     Davi        321          109                  3  3.0  4.0  8.20   
7   Daniel        308          101                  2  3.0  4.0  7.90   
8  Marcelo        302          102                  1  2.0  1.5  8.00   

   Research  Approval  
0         1         1  
1         1         1  
2         1         1  
3         1         1  
4         0         0  
5         1         1  
6         1         1  
7         0         0  
8         0         0  


In [69]:
X = database.iloc[:,:-1].values
print(X)

[['Lucas' 337 118 4 4.5 4.5 9.65 1]
 ['Ana' 324 107 4 4.0 4.5 8.87 1]
 ['Jose' 316 104 3 3.0 3.5 8.0 1]
 ['Carlos' 322 110 3 3.5 2.5 8.67 1]
 ['Zileide' 314 103 2 2.0 3.0 8.21 0]
 ['Joana' 330 115 5 4.5 3.0 9.34 1]
 ['Davi' 321 109 3 3.0 4.0 8.2 1]
 ['Daniel' 308 101 2 3.0 4.0 7.9 0]
 ['Marcelo' 302 102 1 2.0 1.5 8.0 0]]


In [70]:
y = database.iloc[:,-1].values
print(y)

[1 1 1 1 0 1 1 0 0]


In [71]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
imputer = imputer.fit_transform(X[:,1:])
print(imputer)

[[337.   118.     4.     4.5    4.5    9.65   1.  ]
 [324.   107.     4.     4.     4.5    8.87   1.  ]
 [316.   104.     3.     3.     3.5    8.     1.  ]
 [322.   110.     3.     3.5    2.5    8.67   1.  ]
 [314.   103.     2.     2.     3.     8.21   0.  ]
 [330.   115.     5.     4.5    3.     9.34   1.  ]
 [321.   109.     3.     3.     4.     8.2    1.  ]
 [308.   101.     2.     3.     4.     7.9    0.  ]
 [302.   102.     1.     2.     1.5    8.     0.  ]]


In [72]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
print(X)

[[6 337 118 4 4.5 4.5 9.65 1]
 [0 324 107 4 4.0 4.5 8.87 1]
 [5 316 104 3 3.0 3.5 8.0 1]
 [1 322 110 3 3.5 2.5 8.67 1]
 [8 314 103 2 2.0 3.0 8.21 0]
 [4 330 115 5 4.5 3.0 9.34 1]
 [3 321 109 3 3.0 4.0 8.2 1]
 [2 308 101 2 3.0 4.0 7.9 0]
 [7 302 102 1 2.0 1.5 8.0 0]]


In [73]:
X = X[:,1:]

In [74]:
D = pd.get_dummies(X[:,0])
X = np.insert(X, 0, D.values, axis=1)
print(X)

[[0 0 0 0 0 0 0 0 1 337 118 4 4.5 4.5 9.65 1]
 [0 0 0 0 0 0 0 1 0 324 107 4 4.0 4.5 8.87 1]
 [0 0 0 0 1 0 0 0 0 316 104 3 3.0 3.5 8.0 1]
 [0 0 1 0 0 0 0 0 0 322 110 3 3.5 2.5 8.67 1]
 [0 0 0 0 0 0 1 0 0 314 103 2 2.0 3.0 8.21 0]
 [0 0 0 1 0 0 0 0 0 330 115 5 4.5 3.0 9.34 1]
 [0 1 0 0 0 0 0 0 0 321 109 3 3.0 4.0 8.2 1]
 [0 0 0 0 0 1 0 0 0 308 101 2 3.0 4.0 7.9 0]
 [1 0 0 0 0 0 0 0 0 302 102 1 2.0 1.5 8.0 0]]


In [75]:
from sklearn.model_selection import train_test_split
XTrain, xTest, yTrain, yTest = train_test_split(X, y, test_size = 0.2)
print(XTrain)

[[0 0 0 0 1 0 0 0 0 316 104 3 3.0 3.5 8.0 1]
 [0 0 0 0 0 0 0 0 1 337 118 4 4.5 4.5 9.65 1]
 [0 0 0 0 0 1 0 0 0 308 101 2 3.0 4.0 7.9 0]
 [0 0 0 1 0 0 0 0 0 330 115 5 4.5 3.0 9.34 1]
 [0 0 1 0 0 0 0 0 0 322 110 3 3.5 2.5 8.67 1]
 [1 0 0 0 0 0 0 0 0 302 102 1 2.0 1.5 8.0 0]
 [0 0 0 0 0 0 0 1 0 324 107 4 4.0 4.5 8.87 1]]


In [76]:
print(xTest)

[[0 0 0 0 0 0 1 0 0 314 103 2 2.0 3.0 8.21 0]
 [0 1 0 0 0 0 0 0 0 321 109 3 3.0 4.0 8.2 1]]
