In [104]:
import numpy as np
import pandas as pd
import tensorflow as tf
import sklearn as sk

In [105]:
tf.__version__

'2.8.0'

https://www.kaggle.com/fedesoriano/stroke-prediction-dataset

In [106]:
dataset = pd.read_csv("stroke.csv")

dataset

id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes   
1     51676  Female  61.0             0              0          Yes   
2     31112    Male  80.0             0              1          Yes   
3     60182  Female  49.0             0              0          Yes   
4      1665  Female  79.0             1              0          Yes   
...     ...     ...   ...           ...            ...          ...   
5105  18234  Female  80.0             1              0          Yes   
5106  44873  Female  81.0             0              0          Yes   
5107  19723  Female  35.0             0              0          Yes   
5108  37544    Male  51.0             0              0          Yes   
5109  44679  Female  44.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked   
1     Self-employed          Rural             202.21   NaN     never smoked   
2           Private          Rural             105.92  32.5     never smoked   
3           Private          Urban             171.23  34.4           smokes   
4     Self-employed          Rural             174.12  24.0     never smoked   
...             ...            ...                ...   ...              ...   
5105        Private          Urban              83.75   NaN     never smoked   
5106  Self-employed          Urban             125.20  40.0     never smoked   
5107  Self-employed          Rural              82.99  30.6     never smoked   
5108        Private          Rural             166.29  25.6  formerly smoked   
5109       Govt_job          Urban              85.28  26.2          Unknown   

      stroke  
0          1  
1          1  
2          1  
3          1  
4          1  
...      ...  
5105       0  
5106       0  
5107       0  
5108       0  
5109       0  

[5110 rows x 12 columns]

In [107]:
dataset[dataset.isnull().any(axis=1)]

id  gender   age  hypertension  heart_disease ever_married  \
1     51676  Female  61.0             0              0          Yes   
8     27419  Female  59.0             0              0          Yes   
13     8213    Male  78.0             0              1          Yes   
19    25226    Male  57.0             0              1           No   
27    61843    Male  58.0             0              0          Yes   
...     ...     ...   ...           ...            ...          ...   
5039  42007    Male  41.0             0              0           No   
5048  28788    Male  40.0             0              0          Yes   
5093  32235  Female  45.0             1              0          Yes   
5099   7293    Male  40.0             0              0          Yes   
5105  18234  Female  80.0             1              0          Yes   

          work_type Residence_type  avg_glucose_level  bmi   smoking_status  \
1     Self-employed          Rural             202.21  NaN     never smoked   
8           Private          Rural              76.15  NaN          Unknown   
13          Private          Urban             219.84  NaN          Unknown   
19         Govt_job          Urban             217.08  NaN          Unknown   
27          Private          Rural             189.84  NaN          Unknown   
...             ...            ...                ...  ...              ...   
5039        Private          Rural              70.15  NaN  formerly smoked   
5048        Private          Urban             191.15  NaN           smokes   
5093       Govt_job          Rural              95.02  NaN           smokes   
5099        Private          Rural              83.94  NaN           smokes   
5105        Private          Urban              83.75  NaN     never smoked   

      stroke  
1          1  
8          1  
13         1  
19         1  
27         1  
...      ...  
5039       0  
5048       0  
5093       0  
5099       0  
5105       0  

[201 rows x 12 columns]

In [108]:
dataset[dataset.isnull().any(axis=1)] 

id  gender   age  hypertension  heart_disease ever_married  \
1     51676  Female  61.0             0              0          Yes   
8     27419  Female  59.0             0              0          Yes   
13     8213    Male  78.0             0              1          Yes   
19    25226    Male  57.0             0              1           No   
27    61843    Male  58.0             0              0          Yes   
...     ...     ...   ...           ...            ...          ...   
5039  42007    Male  41.0             0              0           No   
5048  28788    Male  40.0             0              0          Yes   
5093  32235  Female  45.0             1              0          Yes   
5099   7293    Male  40.0             0              0          Yes   
5105  18234  Female  80.0             1              0          Yes   

          work_type Residence_type  avg_glucose_level  bmi   smoking_status  \
1     Self-employed          Rural             202.21  NaN     never smoked   
8           Private          Rural              76.15  NaN          Unknown   
13          Private          Urban             219.84  NaN          Unknown   
19         Govt_job          Urban             217.08  NaN          Unknown   
27          Private          Rural             189.84  NaN          Unknown   
...             ...            ...                ...  ...              ...   
5039        Private          Rural              70.15  NaN  formerly smoked   
5048        Private          Urban             191.15  NaN           smokes   
5093       Govt_job          Rural              95.02  NaN           smokes   
5099        Private          Rural              83.94  NaN           smokes   
5105        Private          Urban              83.75  NaN     never smoked   

      stroke  
1          1  
8          1  
13         1  
19         1  
27         1  
...      ...  
5039       0  
5048       0  
5093       0  
5099       0  
5105       0  

[201 rows x 12 columns]

In [109]:
dataset = dataset.dropna()

dataset

id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes   
2     31112    Male  80.0             0              1          Yes   
3     60182  Female  49.0             0              0          Yes   
4      1665  Female  79.0             1              0          Yes   
5     56669    Male  81.0             0              0          Yes   
...     ...     ...   ...           ...            ...          ...   
5104  14180  Female  13.0             0              0           No   
5106  44873  Female  81.0             0              0          Yes   
5107  19723  Female  35.0             0              0          Yes   
5108  37544    Male  51.0             0              0          Yes   
5109  44679  Female  44.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked   
2           Private          Rural             105.92  32.5     never smoked   
3           Private          Urban             171.23  34.4           smokes   
4     Self-employed          Rural             174.12  24.0     never smoked   
5           Private          Urban             186.21  29.0  formerly smoked   
...             ...            ...                ...   ...              ...   
5104       children          Rural             103.08  18.6          Unknown   
5106  Self-employed          Urban             125.20  40.0     never smoked   
5107  Self-employed          Rural              82.99  30.6     never smoked   
5108        Private          Rural             166.29  25.6  formerly smoked   
5109       Govt_job          Urban              85.28  26.2          Unknown   

      stroke  
0          1  
2          1  
3          1  
4          1  
5          1  
...      ...  
5104       0  
5106       0  
5107       0  
5108       0  
5109       0  

[4909 rows x 12 columns]

In [110]:
x = dataset.iloc[:, 1:-1]
y = dataset.iloc[:, -1]

x

gender   age  hypertension  heart_disease ever_married      work_type  \
0       Male  67.0             0              1          Yes        Private   
2       Male  80.0             0              1          Yes        Private   
3     Female  49.0             0              0          Yes        Private   
4     Female  79.0             1              0          Yes  Self-employed   
5       Male  81.0             0              0          Yes        Private   
...      ...   ...           ...            ...          ...            ...   
5104  Female  13.0             0              0           No       children   
5106  Female  81.0             0              0          Yes  Self-employed   
5107  Female  35.0             0              0          Yes  Self-employed   
5108    Male  51.0             0              0          Yes        Private   
5109  Female  44.0             0              0          Yes       Govt_job   

     Residence_type  avg_glucose_level   bmi   smoking_status  
0             Urban             228.69  36.6  formerly smoked  
2             Rural             105.92  32.5     never smoked  
3             Urban             171.23  34.4           smokes  
4             Rural             174.12  24.0     never smoked  
5             Urban             186.21  29.0  formerly smoked  
...             ...                ...   ...              ...  
5104          Rural             103.08  18.6          Unknown  
5106          Urban             125.20  40.0     never smoked  
5107          Rural              82.99  30.6     never smoked  
5108          Rural             166.29  25.6  formerly smoked  
5109          Urban              85.28  26.2          Unknown  

[4909 rows x 10 columns]

In [111]:
x.dtypes

gender                object
age                  float64
hypertension           int64
heart_disease          int64
ever_married          object
work_type             object
Residence_type        object
avg_glucose_level    float64
bmi                  float64
smoking_status        object
dtype: object

In [112]:
x['smoking_status'].unique()

array(['formerly smoked', 'never smoked', 'smokes', 'Unknown'],
      dtype=object)

In [113]:
from sklearn.preprocessing import LabelEncoder

cols = ['ever_married', 'Residence_type'] 
le = LabelEncoder()
x[cols] = x[cols].apply(le.fit_transform)

x.head(10)

gender   age  hypertension  heart_disease  ever_married      work_type  \
0     Male  67.0             0              1             1        Private   
2     Male  80.0             0              1             1        Private   
3   Female  49.0             0              0             1        Private   
4   Female  79.0             1              0             1  Self-employed   
5     Male  81.0             0              0             1        Private   
6     Male  74.0             1              1             1        Private   
7   Female  69.0             0              0             0        Private   
9   Female  78.0             0              0             1        Private   
10  Female  81.0             1              0             1        Private   
11  Female  61.0             0              1             1       Govt_job   

    Residence_type  avg_glucose_level   bmi   smoking_status  
0                1             228.69  36.6  formerly smoked  
2                0             105.92  32.5     never smoked  
3                1             171.23  34.4           smokes  
4                0             174.12  24.0     never smoked  
5                1             186.21  29.0  formerly smoked  
6                0              70.09  27.4     never smoked  
7                1              94.39  22.8     never smoked  
9                1              58.57  24.2          Unknown  
10               0              80.43  29.7     never smoked  
11               0             120.46  36.8           smokes

In [114]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder 

#https://towardsdatascience.com/columntransformer-in-scikit-for-labelencoding-and-onehotencoding-in-machine-learning-c6255952731b
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), ['gender', 'work_type', 'smoking_status'])], 
                       remainder='passthrough')
x = ct.fit_transform(x)

x[0]

array([  0.  ,   1.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ,   0.  ,
         0.  ,   1.  ,   0.  ,   0.  ,  67.  ,   0.  ,   1.  ,   1.  ,
         1.  , 228.69,  36.6 ])

In [115]:
columns = ['ohe1', 'ohe2', 'ohe3', 'ohe4', 'ohe5', 'ohe6', 'ohe7', 'ohe8', 'ohe9', 'ohe10', 'ohe11', 
           'ohe12', 'age', 'hypertension', 'heart_disease', 'ever_married', 'Residence_type', 
           'avg_glucose_level', 'bmi']
pd.DataFrame(x, columns=columns)

ohe1  ohe2  ohe3  ohe4  ohe5  ohe6  ohe7  ohe8  ohe9  ohe10  ohe11  \
0      0.0   1.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0    1.0    0.0   
1      0.0   1.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0    0.0    1.0   
2      1.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0    0.0    0.0   
3      1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0    0.0    1.0   
4      0.0   1.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0    1.0    0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...    ...   
4904   1.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0    0.0    0.0   
4905   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0    0.0    1.0   
4906   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0    0.0    1.0   
4907   0.0   1.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0    1.0    0.0   
4908   1.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   1.0    0.0    0.0   

      ohe12   age  hypertension  heart_disease  ever_married  Residence_type  \
0       0.0  67.0           0.0            1.0           1.0             1.0   
1       0.0  80.0           0.0            1.0           1.0             0.0   
2       1.0  49.0           0.0            0.0           1.0             1.0   
3       0.0  79.0           1.0            0.0           1.0             0.0   
4       0.0  81.0           0.0            0.0           1.0             1.0   
...     ...   ...           ...            ...           ...             ...   
4904    0.0  13.0           0.0            0.0           0.0             0.0   
4905    0.0  81.0           0.0            0.0           1.0             1.0   
4906    0.0  35.0           0.0            0.0           1.0             0.0   
4907    0.0  51.0           0.0            0.0           1.0             0.0   
4908    0.0  44.0           0.0            0.0           1.0             1.0   

      avg_glucose_level   bmi  
0                228.69  36.6  
1                105.92  32.5  
2                171.23  34.4  
3                174.12  24.0  
4                186.21  29.0  
...                 ...   ...  
4904             103.08  18.6  
4905             125.20  40.0  
4906              82.99  30.6  
4907             166.29  25.6  
4908              85.28  26.2  

[4909 rows x 19 columns]

In [116]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.9)

In [117]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

x_train

array([[ 0.8304548 , -0.8304548 ,  0.        , ..., -1.0416844 ,
        -0.74435941, -0.62990925],
       [-1.20415946,  1.20415946,  0.        , ...,  0.95998366,
        -0.6430538 , -0.41312472],
       [-1.20415946,  1.20415946,  0.        , ...,  0.95998366,
        -0.57469109,  0.52247168],
       ...,
       [ 0.8304548 , -0.8304548 ,  0.        , ...,  0.95998366,
         0.50400312, -1.43999882],
       [-1.20415946,  1.20415946,  0.        , ...,  0.95998366,
        -0.53283131,  1.90304685],
       [ 0.8304548 , -0.8304548 ,  0.        , ...,  0.95998366,
        -0.50186994,  0.00903463]])

In [118]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [119]:
ann.fit(x_train, y_train, batch_size=32, epochs=20)

Epoch 1/20
16/16 [==============================] - 1s 3ms/step - loss: 0.6434 - accuracy: 0.6776
Epoch 2/20
16/16 [==============================] - 0s 3ms/step - loss: 0.5562 - accuracy: 0.7571
Epoch 3/20
16/16 [==============================] - 0s 3ms/step - loss: 0.4853 - accuracy: 0.8367
Epoch 4/20
16/16 [==============================] - 0s 3ms/step - loss: 0.4286 - accuracy: 0.8980
Epoch 5/20
16/16 [==============================] - 0s 3ms/step - loss: 0.3834 - accuracy: 0.9245
Epoch 6/20
16/16 [==============================] - 0s 3ms/step - loss: 0.3450 - accuracy: 0.9408
Epoch 7/20
16/16 [==============================] - 0s 3ms/step - loss: 0.3131 - accuracy: 0.9449
Epoch 8/20
16/16 [==============================] - 0s 4ms/step - loss: 0.2868 - accuracy: 0.9531
Epoch 9/20
16/16 [==============================] - 0s 4ms/step - loss: 0.2651 - accuracy: 0.9531
Epoch 10/20
16/16 [==============================] - 0s 4ms/step - loss: 0.2473 - accuracy: 0.9531
Epoch 11/20
16/16 [

In [120]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)

pred_array = 1 * y_pred.reshape(len(y_pred), 1)
test_array = y_test.values.reshape(len(y_test), 1)

np.concatenate([pred_array, test_array], axis=1)

array([[0, 0],
       [0, 0],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [0, 0]])

In [121]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred) 
#vn, fp(predict 1, correct is 0), fn (predict 0, correct is 1), vp

cm

array([[4233,    0],
       [ 186,    0]])

In [122]:
accuracy_score(y_test, y_pred)

0.957909029192125

In [123]:
dataset['stroke'].value_counts()

0    4700
1     209
Name: stroke, dtype: int64